"""
Project model - represents a software project being built.
"""
from datetime import datetime
from enum import Enum
from typing import Optional, List
from sqlalchemy import Column, String, DateTime, Text, Integer, JSON, Enum as SQLEnum
from sqlalchemy.orm import relationship
from app.core.db import Base
import uuid


class ProjectStatus(str, Enum):
    """Project lifecycle states."""
    NEW = "new"
    PLANNING = "planning"
    CODING = "coding"
    TESTING = "testing"
    DEBUGGING = "debugging"
    DEPLOYING = "deploying"
    READY = "ready"
    DEPLOYED = "deployed"
    FAILED = "failed"
    PAUSED = "paused"


class Project(Base):
    """Software project being built by the system."""
    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    prompt = Column(Text, nullable=False)  # Original user prompt

    status = Column(SQLEnum(ProjectStatus), default=ProjectStatus.NEW, nullable=False)

    # User/owner info
    user_id = Column(String, nullable=False, default="system")

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Project spec generated by planner
    spec = Column(JSON, nullable=True)

    # Project workspace path
    workspace_path = Column(String, nullable=True)

    # Repository info
    repo_url = Column(String, nullable=True)
    repo_branch = Column(String, nullable=True)

    # Statistics
    total_tasks = Column(Integer, default=0)
    completed_tasks = Column(Integer, default=0)
    failed_tasks = Column(Integer, default=0)

    # Configuration overrides
    config_overrides = Column(JSON, nullable=True)

    # Error tracking
    error_count = Column(Integer, default=0)
    last_error = Column(Text, nullable=True)

    # Relationships
    tasks = relationship("Task", back_populates="project", cascade="all, delete-orphan")
    events = relationship("Event", back_populates="project", cascade="all, delete-orphan")
    artifacts = relationship("Artifact", back_populates="project", cascade="all, delete-orphan")

    def to_dict(self):
        """Convert project to dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "prompt": self.prompt,
            "status": self.status.value,
            "user_id": self.user_id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "spec": self.spec,
            "workspace_path": self.workspace_path,
            "repo_url": self.repo_url,
            "repo_branch": self.repo_branch,
            "total_tasks": self.total_tasks,
            "completed_tasks": self.completed_tasks,
            "failed_tasks": self.failed_tasks,
            "error_count": self.error_count,
            "last_error": self.last_error,
        }
